import paramiko, re

class BatchSysMngError(Exception):
    """ Abstract Class to manage exception of batch system management module."""
    pass

class BatchCmdError(BatchSysMngError):
    """ Class to manage errors generated by batch system commands.

        Attributes:
            data -- input data
            msg  -- error message
    """

    def __init__(self, msg):
        self.msg = msg
 
    def __str__(self):
        return str(self.msg)

class JobNotFoundError(BatchSysMngError):
    """ Class to manage errors generated by batch system commands.

        Attributes:
            data -- input data
            msg  -- error message
    """

    def __init__(self, msg):
        self.msg = msg

    def __str__(self):
        return str(self.msg)

################################
## AbstractBatchSystem        ##
################################
class AbstractBatchSystem:

    """Abstract class to manage different batch systems"""
   
    def __init__(self, batch_sys, host, admin_name, admin_pass):
        self.my_batch_sys = batch_sys
        self.my_host = host
        self.my_admin_name = admin_name
        self.my_admin_pass = admin_pass

# Public interface

    def del_job_from_batch_id(self, batch_id):
        pass

    def __del__(self):
        pass

# Private functions

    def get_batch_jid_from_cream_jid(self, cream_id):
        pass


################################
## LSFBatchSys                ##
################################

class LSFBatchSys(AbstractBatchSystem):
    """Class to manage LSF batch systems"""
 
    ssh_connection = paramiko.SSHClient()
  
    def __init__(self, batch_sys, my_host, lsf_admin_name, lsf_admin_pass):
        self.batch_sys = batch_sys
        self.lsf_host = my_host
        self.lsf_admin = lsf_admin_name
        self.lsf_pass = lsf_admin_pass
        print "Get ssh connection with cream ce to manage batch system commands"
        self.ssh_connection.set_missing_host_key_policy(paramiko.AutoAddPolicy())  #don't ask for acceptance of foreign host key (auto accept)
        self.ssh_connection.connect(self.lsf_host, username=self.lsf_admin, password=self.lsf_pass)

# Public interface

    def __del__(self):
        self.ssh_connection.close()

    def del_job_from_batch_id(self, lsf_jid):

        stdin, stdout, stderr = self.ssh_connection.exec_command("bkill " + lsf_jid)

        error = stderr.readlines()
        if error != []:
            raise BatchCmdError(error)

        print "Cream job with lsf jid " + lsf_jid + " has been deleted!"


    def del_job_from_cream_id(self, cream_id):
        
        lsf_job_id = self.get_batch_jid_from_cream_jid(cream_id)
        self.del_job_from_batch_id(lsf_job_id)       

# Private functions

    def get_batch_jid_from_cream_jid(self, cream_id):

        print "CREAM Job ID is: " + cream_id
        cream_num_jid = cream_id.split("CREAM")[1]

        stdin, stdout, stderr = self.ssh_connection.exec_command("qstat -al")

        error = stderr.readlines()
        if error != []:
            raise BatchCmdError(error)

        output = stdout.read()

        lsf_jid = "not_set"
        for line in output.split('\n'):
                if cream_num_jid in line:
                        m = re.search('(?<=; Id = ).*', line)
                        lsf_jid = m.group(0)

        if lsf_jid is "not_set":
                raise JobNotFoundError("Cream job with jid " + cream_id + " has not been found on the LSF server! (`qstat -al` didn't report it)")

        return lsf_jid



################################
## PBSBatchSys                ##
################################

class PBSBatchSys(AbstractBatchSystem):
    """Class to manage PBS-Torque batch systems"""

    ssh_connection = paramiko.SSHClient() 
  
    def __init__(self, batch_sys, my_host, torque_admin_name, torque_admin_pass):
        self.batch_sys = batch_sys
        self.torque_host = my_host
        self.torque_admin = torque_admin_name
        self.torque_pass = torque_admin_pass
        print "batch_sys " + self.batch_sys
        print "torque_host " + self.torque_host
        print "torque_admin " + self.torque_admin
        print "torque_pass " + self.torque_pass
        print "Get ssh connection with cream ce to manage batch system commands"
        self.ssh_connection.set_missing_host_key_policy(paramiko.AutoAddPolicy())  #don't ask for acceptance of foreign host key (auto accept)
        self.ssh_connection.connect(self.torque_host, username=self.torque_admin, password=self.torque_pass)

# Public interface

    def __del__(self):
        self.ssh_connection.close()

    def del_job_from_batch_id(self, torque_jid):

        stdin, stdout, stderr = self.ssh_connection.exec_command("qdel " + torque_jid)

        error = stderr.readlines()
        if error != []:
            raise BatchCmdError(error)
       
        print "Cream job with torque jid " + torque_jid + " has been deleted!"


    def del_job_from_cream_id(self, cream_id):
        
        torque_job_id = self.get_batch_jid_from_cream_jid(cream_id)
        self.del_job_from_batch_id(torque_job_id)       

# Private functions

    def get_batch_jid_from_cream_jid(self, cream_id):

        print "CREAM Job ID is: " + cream_id
        cream_num_jid = cream_id.split("CREAM")[1]
        print "CREAM Numeric Job Identifier is: " + cream_num_jid

        print "Verify if job " + cream_num_jid + " exists using qstat"
        stdin, stdout, stderr = self.ssh_connection.exec_command("qstat")

        error = stderr.readlines()
        if error != []:
            raise BatchCmdError(error)

        output = stdout.read()

        torque_jid = "not_set"
        for line in output.split('\n'):
                if cream_num_jid in line:
                        torque_jid = line.split(' ')[0]
                        torque_jid = torque_jid.split('.')[0]
                        print "TORQUE jid is: " + torque_jid

        if torque_jid is "not_set":
                raise JobNotFoundError("Cream job with jid " + cream_id + " has not been found on the Torque server! (qstat didn't report it)")

        return torque_jid


################################
## BatchSystemFactory         ##
################################

class BatchSystemFactory:
 
    def __init__(self, batch_sys, my_host, batch_admin_name, batch_admin_pass):
        self.batch_sys = batch_sys
        self.my_host = my_host
        self.batch_admin_name = batch_admin_name
        self.batch_admin_pass = batch_admin_pass

    def getBatchSystemMng(self):

        my_batch_sys = AbstractBatchSystem(self.batch_sys, self.my_host, self.batch_admin_name, self.batch_admin_pass)

        if self.batch_sys == "lsf":
            my_batch_sys = LSFBatchSys(self.batch_sys, self.my_host, self.batch_admin_name, self.batch_admin_pass)
            return my_batch_sys
        elif self.batch_sys == "pbs":
            print "Get batch sys mng for PBS"
            print "batch_sys " + self.batch_sys
            print "batch_host " + self.my_host
            print "batch_admin_name " + self.batch_admin_name
            print "batch_admin_pass " + self.batch_admin_pass
            my_batch_sys = PBSBatchSys(self.batch_sys, self.my_host, self.batch_admin_name, self.batch_admin_pass)
            return my_batch_sys

        return batch_sys + "batch system not supported"
